---
# BGP config with resource modules

- name: Cisco NX-OS
  block:
    - name: Pull current config
      cisco.nxos.nxos_facts:
        gather_subset: min
        gather_network_resources: 
          - "bgp_global"
      register: _nxos_facts
    - debug: 
        var: _nxos_facts.ansible_facts.ansible_network_resources | to_nice_yaml
        verbosity: 2
    - name: BGP config with resource module
      cisco.nxos.nxos_bgp_global:
        config: "{{ bgp_nxos_global_config }}"
        state: "{{ bgp_rm_state }}"
      register: _nxos_bgp_config
    - debug: 
        var: _nxos_bgp_config
        verbosity: 2
    # deprecated, removed after 2023-02-24
    #- name: BGP neighbor address-family configuration
    #  cisco.nxos.nxos_bgp_neighbor_af:
    #    "{{ item }}"
    #  loop: "{{ bgp_nxos_af_config }}"
  when: ansible_network_os == 'nxos'
  tags: [always]

- name: Cisco IOS
  block:
    - name: Pull current config
      cisco.ios.ios_facts:
        gather_subset: min
        gather_network_resources: 
          - "bgp_global"
      register: _ios_facts
    - debug: 
        var: _ios_facts.ansible_facts.ansible_network_resources | to_nice_yaml
        verbosity: 2
    - name: BGP config with resource module
      cisco.ios.ios_bgp_global:
        config: "{{ bgp_nxos_global_config }}"
        state: "{{ bgp_rm_state }}"
      register: _ios_bgp_config
    - debug: 
        var: _ios_bgp_config
        verbosity: 2
  when: ansible_network_os == 'ios'
  tags: [always]